# scratch file, used grammar should be in the readme

<program> ::= <comand_list> <end>
            | <end>

<comand_list> ::= <comand_list> <and_or>

<and_or> ::= <pipeline>
           | <and_or> '&&' <pipeline>
           | <and_or> '||' <pipeline>

<pipeline> ::= <command>
             | <pipeline> '|' <command>



<end> ::= '\n' | '\r\n' | '\0'

<line> ::= <cmd> <end>

<cmd> ::= <tiem>
        | <cmd> <tiem>

<redirection> ::=  '>' <word>
                |  '<' <word>
                |  <number> '>' <word>
                |  <number> '<' <word>
                |  '>>' <word>
                |  <number> '>>' <word>
                |  '<<' <word>
                |  <number> '<<' <word>

line := cmd { `|` cmd } NEWLINE;

cmd := item { item } ;

item := [ `<<` | `<` | `>>` | `>` ] STRING ;
